image: node:latest

before_script:
  - cd client
  - npm install
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - build
  - test
  - staging
  - production

build:
  stage: build
  script:
    - CI=false npm run build

test:
  stage: test
  script:
    - CI=false npm run test

staging:
  stage: staging
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_DEVELOPMENT --api-key=$HEROKU_API_KEY
  only:
    - development

production:
  stage: production
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - master
